"""add_source_health_state

Revision ID: 083533b83583
Revises: 90a7c33566b2
Create Date: 2026-02-01 15:34:52.994625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083533b83583'
down_revision = '90a7c33566b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_health_states',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cookie_jar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_index(op.f('ix_source_health_states_source_id'), 'source_health_states', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_health_states_source_id'), table_name='source_health_states')
    op.drop_table('source_health_states')
    # ### end Alembic commands ###
