"""add_narrative_id_fk

Revision ID: 67fe67e435b8
Revises: 0001_initial
Create Date: 2026-01-27 23:01:51.408661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67fe67e435b8'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('current_state', sa.Enum('EMERGING', 'ACTIVE', 'SATURATED', 'FADING', 'DORMANT', name='narrativestate'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_reliability',
    sa.Column('source_ref', sa.String(), nullable=False),
    sa.Column('trust_index', sa.Float(), nullable=False),
    sa.Column('total_mentions', sa.Integer(), nullable=False),
    sa.Column('confirmed_mentions', sa.Integer(), nullable=False),
    sa.Column('noise_mentions', sa.Integer(), nullable=False),
    sa.Column('average_lifespan_minutes', sa.Float(), nullable=False),
    sa.Column('rolling_confirmed_rate', sa.Float(), nullable=False),
    sa.Column('rolling_noise_rate', sa.Float(), nullable=False),
    sa.Column('persistence_alignment', sa.Float(), nullable=False),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source_ref')
    )
    op.create_table('narrative_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('narrative_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mention_velocity', sa.Float(), nullable=False),
    sa.Column('active_duration_minutes', sa.Float(), nullable=False),
    sa.Column('current_state', sa.Enum('EMERGING', 'ACTIVE', 'SATURATED', 'FADING', 'DORMANT', name='narrativestate'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_metrics_narrative_id'), 'narrative_metrics', ['narrative_id'], unique=False)
    op.create_table('cluster_assignments',
    sa.Column('information_event_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['narrative_clusters.id'], name='fk_cluster_assignments_cluster_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['information_event_id'], ['information_events.id'], name='fk_cluster_assignments_information_event_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('information_event_id')
    )
    op.create_index(op.f('ix_cluster_assignments_cluster_id'), 'cluster_assignments', ['cluster_id'], unique=False)
    op.create_table('narrative_reliability_snapshots',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reliability_status', sa.Enum('STRONG', 'MODERATE', 'WEAK', 'NOISE', name='reliability_status'), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['narrative_clusters.id'], name='fk_narrative_reliability_snapshots_cluster_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_narrative_reliability_snapshots_cluster_id'), 'narrative_reliability_snapshots', ['cluster_id'], unique=False)
    op.create_index('ix_narrative_reliability_snapshots_cluster_time', 'narrative_reliability_snapshots', ['cluster_id', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_narrative_reliability_snapshots_snapshot_at'), 'narrative_reliability_snapshots', ['snapshot_at'], unique=False)
    op.add_column('narrative_clusters', sa.Column('narrative_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_narrative_clusters_narrative_id'), 'narrative_clusters', ['narrative_id'], unique=False)
    op.create_foreign_key(None, 'narrative_clusters', 'narratives', ['narrative_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'narrative_clusters', type_='foreignkey')
    op.drop_index(op.f('ix_narrative_clusters_narrative_id'), table_name='narrative_clusters')
    op.drop_column('narrative_clusters', 'narrative_id')
    op.drop_index(op.f('ix_narrative_reliability_snapshots_snapshot_at'), table_name='narrative_reliability_snapshots')
    op.drop_index('ix_narrative_reliability_snapshots_cluster_time', table_name='narrative_reliability_snapshots')
    op.drop_index(op.f('ix_narrative_reliability_snapshots_cluster_id'), table_name='narrative_reliability_snapshots')
    op.drop_table('narrative_reliability_snapshots')
    op.drop_index(op.f('ix_cluster_assignments_cluster_id'), table_name='cluster_assignments')
    op.drop_table('cluster_assignments')
    op.drop_index(op.f('ix_narrative_metrics_narrative_id'), table_name='narrative_metrics')
    op.drop_table('narrative_metrics')
    op.drop_table('source_reliability')
    op.drop_table('narratives')
    # ### end Alembic commands ###
