"""create_inversion_feeds

Revision ID: 90a7c33566b2
Revises: 67fe67e435b8
Create Date: 2026-02-01 09:14:56.265965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90a7c33566b2'
down_revision = '67fe67e435b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inversion_feeds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('feed_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('gin_inversion_feeds_metadata', 'inversion_feeds', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('gin_inversion_feeds_payload', 'inversion_feeds', ['payload'], unique=False, postgresql_using='gin')
    op.create_index('ix_inversion_feeds_created_at', 'inversion_feeds', ['created_at'], unique=False)
    op.create_index('ix_inversion_feeds_external_id', 'inversion_feeds', ['external_id'], unique=True, postgresql_where=sa.text('external_id IS NOT NULL'))
    op.create_index('ix_inversion_feeds_status', 'inversion_feeds', ['status'], unique=False)
    op.create_index('ix_inversion_feeds_symbol', 'inversion_feeds', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inversion_feeds_symbol', table_name='inversion_feeds')
    op.drop_index('ix_inversion_feeds_status', table_name='inversion_feeds')
    op.drop_index('ix_inversion_feeds_external_id', table_name='inversion_feeds', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('ix_inversion_feeds_created_at', table_name='inversion_feeds')
    op.drop_index('gin_inversion_feeds_payload', table_name='inversion_feeds', postgresql_using='gin')
    op.drop_index('gin_inversion_feeds_metadata', table_name='inversion_feeds', postgresql_using='gin')
    op.drop_table('inversion_feeds')
    # ### end Alembic commands ###
